package by.epamtr.airline.controller.command;

public enum CommandName {
	SIGN_IN,
	SIGN_OUT,

	GO_TO_LOGIN_PAGE,
	GO_TO_MAIN_PAGE,
	WRONG_REQUEST,
	
	ADD_USER,
	DELITE_USER,
	UPDATE_USER,
	GET_USERS,
	GET_USER,
	GET_USER_BY_LOGIN,
	GET_USERS_BY_ROLE,
	GET_USERS_BY_FLIGHT_ID,
	ADD_CREW_TO_FLIGHT,
	DELETE_CREW_FROM_FLIGHT,
	
	ADD_FLIGHT,
	DELETE_FLIGHT,
	UPDATE_FLIGHT,
	CHANGE_FLIGHT_STATUS,
	GET_FLIGHTS_BY_STATUS,
	GET_FLIGHTS_BY_USER,
	
	ADD_AIRCRAFT,
	DELETE_AIRCRAFT,
	UPDATE_AIRCRAFT,
	CHANGE_STATUS_AIRCRAFT,
	ADD_AIRCRAFT_TYPE,
	DELETE_AIRCRAFT_TYPE;
}
